### ISSUE TITLE
display not working

### ISSUE THREAD

**Issue by kjames2001** [mklements/OLED_Stats_Docker#4]
My display stoped working, so i stoped the docker container and re-ran it. 

The docker starts with no problems, but when i run "docker exec OLED_Stats status", i get this: "OCI runtime exec failed: exec failed: unable to start container process: exec: "status": executable file not found in $PATH: unknown"

**Comment by kjames2001** [comment]
running python3 stats.py inside docker, just hangs.

**Comment by mklements** [comment]
What hardware are you running?
Have you tried this command and do you get the I2C address - docker exec -t OLED_Stats i2cdetect -y 1

**Comment by kjames2001** [comment]
Yes It did. I was using it just fine a few days ago. And your non docker script works just fine.

**Comment by finnie2006** [comment]
Same problem

**Comment by Macleykun** [comment]
Do: 
```
sudo raspi-config nonint do_spi 0
sudo raspi-config nonint do_i2c 0
```
On the rpi host, and restart the container and see if it works.
Had to reinstall my pi the other day, and noticed i needed to do those.

**Comment by carlos-algms** [comment]
Same here, I'm getting:

```
oled-stats  | Traceback (most recent call last):
oled-stats  |   File "/opt/stats/stats.py", line 24, in <module>
oled-stats  |     start = os.environ['start']
oled-stats  |             ~~~~~~~~~~^^^^^^^^^
oled-stats  |   File "<frozen os>", line 678, in __getitem__
oled-stats  | KeyError: 'start'
oled-stats exited with code 1
```

With this docker-compose.yaml:
```yaml
version: '3.9'
services:
  oled-stats:
    container_name: oled-stats
    image: mklements/oled_stats:latest
    restart: unless-stopped

    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

    privileged: true
    # devices: # With devices, it also doesn't work.
    #   - /dev/i2c-1:dev/i2c-1
    #   - /dev/gpiomem:/dev/gpiomem

    cap_add:
      - SYS_RAWIO

    network_mode: host
```
